// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATGpva3IcZyvQp-yduroN82RGRtzPpVaA',
    appId: '1:52219548078:web:9fcfa3a60c4dfe3772b83f',
    messagingSenderId: '52219548078',
    projectId: 'indexa-96cad',
    authDomain: 'indexa-96cad.firebaseapp.com',
    storageBucket: 'indexa-96cad.appspot.com',
    measurementId: 'G-Q4G8ZL0QNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFRQp2Pkb5jJYeA9oiiU1FWURNMzVjeLg',
    appId: '1:52219548078:android:8ccefff12e424dc672b83f',
    messagingSenderId: '52219548078',
    projectId: 'indexa-96cad',
    storageBucket: 'indexa-96cad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRN8s24eownEuU0pw_hIf_S9_piBczrmk',
    appId: '1:52219548078:ios:cbeb87f0beada64b72b83f',
    messagingSenderId: '52219548078',
    projectId: 'indexa-96cad',
    storageBucket: 'indexa-96cad.appspot.com',
    androidClientId: '52219548078-3a5jqijruiq40dvqt56vpp9d0lke1e9h.apps.googleusercontent.com',
    iosClientId: '52219548078-4tj95od2744fnetcfl0tshbmf376o935.apps.googleusercontent.com',
    iosBundleId: 'com.ICMA.indexa',
  );
}
